/*
 * Copyright (C) 2014 Aurora Cain
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.uncc.genosets.geneontology.obo;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author lucy
 */
public class OboVisualPanel extends javax.swing.JPanel {

    /**
     * Creates new form OboVisualPanel
     */
    public OboVisualPanel() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Select Ontology";
    }

    public JTextField getOntologyTextField() {
        return ontologyTextField;
    }

    public JButton getBrowseButton() {
        return browseButton;
    }

    public JRadioButton getFileRadio() {
        return fileRadio;
    }

    public JLabel getLastUsedDateField() {
        return lastUsedDateField;
    }

    public JLabel getLastUsedNameField() {
        return lastUsedNameField;
    }

    public JRadioButton getLastUsedRadio() {
        return lastUsedRadio;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ontologyTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        fileRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lastUsedRadio = new javax.swing.JRadioButton();
        lastUsedNameField = new javax.swing.JLabel();
        lastUsedDateField = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.jLabel1.text")); // NOI18N

        ontologyTextField.setText(org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.ontologyTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.browseButton.text")); // NOI18N

        buttonGroup1.add(fileRadio);
        fileRadio.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(fileRadio, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.fileRadio.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.jLabel2.text")); // NOI18N

        buttonGroup1.add(lastUsedRadio);
        org.openide.awt.Mnemonics.setLocalizedText(lastUsedRadio, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.lastUsedRadio.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lastUsedNameField, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.lastUsedNameField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lastUsedDateField, org.openide.util.NbBundle.getMessage(OboVisualPanel.class, "OboVisualPanel.lastUsedDateField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ontologyTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lastUsedRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastUsedDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lastUsedNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileRadio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(ontologyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastUsedRadio)
                    .addComponent(lastUsedNameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastUsedDateField)
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fileRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastUsedDateField;
    private javax.swing.JLabel lastUsedNameField;
    private javax.swing.JRadioButton lastUsedRadio;
    private javax.swing.JTextField ontologyTextField;
    // End of variables declaration//GEN-END:variables
}
