/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.pathway;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class LoadPathwayVisualPanel1 extends JPanel {

    PropertyChangeSupport pcs = new PropertyChangeSupport(this);
    /**
     * Creates new form LoadPathwayVisualPanel1
     */
    public LoadPathwayVisualPanel1() {
        initComponents();
        locationIdColumn.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_LOCATION_ID, null, locationIdColumn.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_LOCATION_ID, null, locationIdColumn.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_LOCATION_ID, null, locationIdColumn.getText());
            }
            
        });
        pathIdColumn.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_LOCATION_ID, null, pathIdColumn.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_LOCATION_ID, null, pathIdColumn.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_LOCATION_ID, null, pathIdColumn.getText());
            }     
        });
        pathNameColumn.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_PATH_NAME_COLUMN, null, pathNameColumn.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_PATH_NAME_COLUMN, null, pathNameColumn.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                firePropertyChange(LoadPathwayWizardPanel1.PROP_PATH_NAME_COLUMN, null, pathNameColumn.getText());
            }
            
        });
    }

    @Override
    public String getName() {
        return "Select Columns";
    }
    
    public void addPropertyChangeListener(PropertyChangeListener listener){
        this.pcs.addPropertyChangeListener(listener);
    }
    
    public void removePropertyChangeListener(PropertyChangeListener listener){
        this.pcs.removePropertyChangeListener(listener);
    }
    
    private void firePropertyChange(String property, String oldValue, String newValue){
        this.pcs.firePropertyChange(property, oldValue, newValue);
    }

    public JTextField getLocationIdColumn() {
        return locationIdColumn;
    }

    public JTextField getPathIdColumn() {
        return pathIdColumn;
    }

    public JTextField getPathNameColumn() {
        return pathNameColumn;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pathNameColumn = new javax.swing.JTextField();
        pathIdColumn = new javax.swing.JTextField();
        locationIdColumn = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoadPathwayVisualPanel1.class, "LoadPathwayVisualPanel1.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(LoadPathwayVisualPanel1.class, "LoadPathwayVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(LoadPathwayVisualPanel1.class, "LoadPathwayVisualPanel1.jLabel3.text")); // NOI18N

        pathNameColumn.setText(org.openide.util.NbBundle.getMessage(LoadPathwayVisualPanel1.class, "LoadPathwayVisualPanel1.pathNameColumn.text")); // NOI18N

        pathIdColumn.setText(org.openide.util.NbBundle.getMessage(LoadPathwayVisualPanel1.class, "LoadPathwayVisualPanel1.pathIdColumn.text")); // NOI18N

        locationIdColumn.setText(org.openide.util.NbBundle.getMessage(LoadPathwayVisualPanel1.class, "LoadPathwayVisualPanel1.locationIdColumn.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(locationIdColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pathIdColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pathNameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathIdColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathNameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(locationIdColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField locationIdColumn;
    private javax.swing.JTextField pathIdColumn;
    private javax.swing.JTextField pathNameColumn;
    // End of variables declaration//GEN-END:variables
}
