/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.parsetsbridge;

import edu.uncc.genosets.parsetsbridge.property.GenoSetsController;
import edu.uncc.genosets.parsetsbridge.property.GenoSetsDataSet;
import edu.uncc.parsets.data.DataSet;
import edu.uncc.parsets.gui.SideBar;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author lucy
 */
public class GenoSetsSideBar extends SideBar {

    private GenoSetsController controller;

    public GenoSetsSideBar(GenoSetsDataSet dataset, GenoSetsController controller) {
        this.controller = controller;
        this.controller.addDataSetListener(this);
        initComponents();
        setDataSet(dataset);
    }

    @Override
    public final void setDataSet(DataSet data) {
        DefaultMutableTreeNode catTree = data.getCategoricalDimensionsAsTree();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
