package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * AnnotationMethod generated by hbm2java
 */
@XmlRootElement
public class AnnotationMethod extends CustomizableEntity implements java.io.Serializable, Cloneable {

    public static final String DEFAULT_NAME = "AnnotationMethod";
    private Integer annotationMethodId;

    private String methodVersion;
    private String methodCategory;
    private String methodType;
    private String methodSourceType;
    private String methodName;
    private String methodDescription;
    private Date runDate;
    private Date loadDate;
    private Boolean obsolete = false;

    public AnnotationMethod() {

    }

    public AnnotationMethod(String methodVersion, String methodCategory, String methodType, String methodSourceType, String methodName, String methodDescription, Date runDate) {
        this.methodVersion = methodVersion;
        this.methodCategory = methodCategory;
        this.methodType = methodType;
        this.methodSourceType = methodSourceType;
        this.methodName = methodName;
        this.methodDescription = methodDescription;
        this.runDate = runDate;
    }


    public Integer getAnnotationMethodId() {
        return this.annotationMethodId;
    }

    public void setAnnotationMethodId(Integer annotationMethodId) {
        this.annotationMethodId = annotationMethodId;
    }

    public String getMethodVersion() {
        return this.methodVersion;
    }

    public void setMethodVersion(String methodVersion) {
        this.methodVersion = methodVersion;
    }

    public String getMethodCategory() {
        return this.methodCategory;
    }

    public void setMethodCategory(String methodCategory) {
        this.methodCategory = methodCategory;
    }

    public String getMethodType() {
        return this.methodType;
    }

    public void setMethodType(String methodType) {
        this.methodType = methodType;
    }

    public String getMethodSourceType() {
        return this.methodSourceType;
    }

    public void setMethodSourceType(String methodSourceType) {
        this.methodSourceType = methodSourceType;
    }

    public String getMethodName() {
        return this.methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    public String getMethodDescription() {
        return this.methodDescription;
    }

    public void setMethodDescription(String methodDescription) {
        this.methodDescription = methodDescription;
    }

    public Date getRunDate() {
        return this.runDate;
    }

    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }

    /**
     * The date the method was actually loaded into genosets
     * @return date
     */
    public Date getLoadDate() {
        return loadDate;
    }

    /**
     * Sets the date the method was actually loaded into genosets.
     * This can differ from the acquistion date.
     * @param loadDate 
     */
    public void setLoadDate(Date loadDate) {
        this.loadDate = loadDate;
    }

    public Boolean getObsolete() {
        return obsolete;
    }

    public void setObsolete(Boolean obsolete) {
        this.obsolete = obsolete;
    }

    @Override
    public AnnotationMethod clone() throws CloneNotSupportedException {
         AnnotationMethod method = (AnnotationMethod) super.clone();
         method.setAnnotationMethodId(null);
         return method;
    }

    @Override
    public String getEntityName() {
        return super.getEntityName();
    }

    @Override
    public String getDefaultName() {
        return AnnotationMethod.DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.annotationMethodId;
    }
}
