package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

/**
 * AssembledUnitAquisition generated by hbm2java
 */
public class AssembledUnitAquisition extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "AssembledUnitAquisition";
    private Integer assembledUnitAquisitionId;
    private Organism organism;
    private MolecularSequence molecularSequence;
    private AnnotationMethod annotationMethod;
    private AssembledUnit assembledUnit;
    private Integer organismId;
    private Integer assembledUnitId;
    private Integer annotationMethodId;
    private String assembledUnitName;

    public AssembledUnitAquisition() {
    }

    public AssembledUnitAquisition(Organism organism, MolecularSequence molecularSequence, AnnotationMethod annotationMethod, AssembledUnit assembledUnit) {
        this.organism = organism;
        this.molecularSequence = molecularSequence;
        this.annotationMethod = annotationMethod;
        this.assembledUnit = assembledUnit;
    }

    public Integer getAssembledUnitAquisitionId() {
        return this.assembledUnitAquisitionId;
    }

    public void setAssembledUnitAquisitionId(Integer assembledUnitAquisitionId) {
        this.assembledUnitAquisitionId = assembledUnitAquisitionId;
    }

    public Organism getOrganism() {
        return this.organism;
    }

    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public MolecularSequence getMolecularSequence() {
        return this.molecularSequence;
    }

    public void setMolecularSequence(MolecularSequence molecularSequence) {
        this.molecularSequence = molecularSequence;
    }

    public AnnotationMethod getAnnotationMethod() {
        return this.annotationMethod;
    }

    public void setAnnotationMethod(AnnotationMethod annotationMethod) {
        this.annotationMethod = annotationMethod;
    }

    public AssembledUnit getAssembledUnit() {
        return this.assembledUnit;
    }

    public void setAssembledUnit(AssembledUnit assembledUnit) {
        this.assembledUnit = assembledUnit;
    }

    public Integer getAnnotationMethodId() {
        return annotationMethodId;
    }

    public void setAnnotationMethodId(Integer annotationMethodId) {
        this.annotationMethodId = annotationMethodId;
    }

    public Integer getAssembledUnitId() {
        return assembledUnitId;
    }

    public void setAssembledUnitId(Integer assembledUnitId) {
        this.assembledUnitId = assembledUnitId;
    }

    public Integer getOrganismId() {
        return organismId;
    }

    public void setOrganismId(Integer organismId) {
        this.organismId = organismId;
    }

    public String getAssembledUnitName() {
        return assembledUnitName;
    }

    public void setAssembledUnitName(String assembledUnitName) {
        this.assembledUnitName = assembledUnitName;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.assembledUnitAquisitionId;
    }
}
