package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

/**
 * AssembledUnitCluster generated by hbm2java
 */
public class AssembledUnitCluster extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "AssembledUnitCluster";
    private Integer assembledUnitClusterId;
    private String clusterCategory;
    private String clusterType;
    private String clusterName;
    private Integer totalAssembledUnitInCluster;

    public AssembledUnitCluster() {
    }

    public AssembledUnitCluster(String clusterCategory, String clusterType, String clusterName, Integer totalAssembledUnitInCluster) {
        this.clusterCategory = clusterCategory;
        this.clusterType = clusterType;
        this.clusterName = clusterName;
        this.totalAssembledUnitInCluster = totalAssembledUnitInCluster;
    }

    public Integer getAssembledUnitClusterId() {
        return this.assembledUnitClusterId;
    }

    public void setAssembledUnitClusterId(Integer assembledUnitClusterId) {
        this.assembledUnitClusterId = assembledUnitClusterId;
    }

    public String getClusterCategory() {
        return this.clusterCategory;
    }

    public void setClusterCategory(String clusterCategory) {
        this.clusterCategory = clusterCategory;
    }

    public String getClusterType() {
        return this.clusterType;
    }

    public void setClusterType(String clusterType) {
        this.clusterType = clusterType;
    }

    public String getClusterName() {
        return this.clusterName;
    }

    public void setClusterName(String clusterName) {
        this.clusterName = clusterName;
    }

    public Integer getTotalAssembledUnitInCluster() {
        return this.totalAssembledUnitInCluster;
    }

    public void setTotalAssembledUnitInCluster(Integer totalAssembledUnitInCluster) {
        this.totalAssembledUnitInCluster = totalAssembledUnitInCluster;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.assembledUnitClusterId;
    }
}
