package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

/**
 * AssembledUnit generated by hbm2java
 */
public class AssembledUnit extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "AssembledUnit";
    private Integer assembledUnitId;
    private Organism organism;
    private Integer organismId;
    private MolecularSequence molecularSequence;
    private Integer molecularSequenceId;
    private String assembledUnitName;
    private String accessionVersion;
    private Integer sequenceLength;
    private String assembledUnitType;
    private String replicatingUnitType;
    private String repUnitName;
    private Integer assembledUnitLength;

    public AssembledUnit() {
    }

    public Integer getAssembledUnitId() {
        return this.assembledUnitId;
    }

    public void setAssembledUnitId(Integer assembledUnitId) {
        this.assembledUnitId = assembledUnitId;
    }

    public Organism getOrganism() {
        return this.organism;
    }

    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public MolecularSequence getMolecularSequence() {
        return this.molecularSequence;
    }

    public void setMolecularSequence(MolecularSequence molecularSequence) {
        this.molecularSequence = molecularSequence;
    }

    public String getAssembledUnitName() {
        return this.assembledUnitName;
    }

    public void setAssembledUnitName(String assembledUnitName) {
        this.assembledUnitName = assembledUnitName;
    }

    public String getAccessionVersion() {
        return accessionVersion;
    }

    public void setAccessionVersion(String accessionVersion) {
        this.accessionVersion = accessionVersion;
    }

    public Integer getSequenceLength() {
        return this.sequenceLength;
    }

    public void setSequenceLength(Integer sequenceLength) {
        this.sequenceLength = sequenceLength;
    }

    public String getAssembledUnitType() {
        return this.assembledUnitType;
    }

    public void setAssembledUnitType(String assembledUnitType) {
        this.assembledUnitType = assembledUnitType;
    }

    public String getReplicatingUnitType() {
        return this.replicatingUnitType;
    }

    public void setReplicatingUnitType(String replicatingUnitType) {
        this.replicatingUnitType = replicatingUnitType;
    }

    public String getRepUnitName() {
        return this.repUnitName;
    }

    public void setRepUnitName(String repUnitName) {
        this.repUnitName = repUnitName;
    }

    public Integer getAssembledUnitLength() {
        return this.assembledUnitLength;
    }

    public void setAssembledUnitLength(Integer assembledUnitLength) {
        this.assembledUnitLength = assembledUnitLength;
    }

    public Integer getOrganismId() {
        return organismId;
    }

    public void setOrganismId(Integer organismId) {
        this.organismId = organismId;
    }

    public Integer getMolecularSequenceId() {
        return molecularSequenceId;
    }

    public void setMolecularSequenceId(Integer molecularSequenceId) {
        this.molecularSequenceId = molecularSequenceId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AssembledUnit other = (AssembledUnit) obj;
        if (this.assembledUnitId != other.assembledUnitId && (this.assembledUnitId == null || !this.assembledUnitId.equals(other.assembledUnitId))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 37 * hash + (this.assembledUnitId != null ? this.assembledUnitId.hashCode() : 0);
        return hash;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.assembledUnitId;
    }
}
