package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

/**
 * BasecallingAnnotation generated by hbm2java
 */
public class BasecallingAnnotation extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "BasecallingAnnotation";
    private Integer basecallingAnnotationId;
    private Organism organism;
    private SeqRead seqRead;
    private AnnotationMethod annotationMethod;
    private Chromatogram chromatogram;

    public BasecallingAnnotation() {
    }

    public BasecallingAnnotation(Organism organism, SeqRead seqRead, AnnotationMethod annotationMethod, Chromatogram chromatogram) {
        this.organism = organism;
        this.seqRead = seqRead;
        this.annotationMethod = annotationMethod;
        this.chromatogram = chromatogram;
    }

    public Integer getBasecallingAnnotationId() {
        return this.basecallingAnnotationId;
    }

    public void setBasecallingAnnotationId(Integer basecallingAnnotationId) {
        this.basecallingAnnotationId = basecallingAnnotationId;
    }

    public Organism getOrganism() {
        return this.organism;
    }

    public void setOrganism(Organism organism) {
        this.organism = organism;
    }

    public SeqRead getSeqRead() {
        return this.seqRead;
    }

    public void setSeqRead(SeqRead seqRead) {
        this.seqRead = seqRead;
    }

    public AnnotationMethod getAnnotationMethod() {
        return this.annotationMethod;
    }

    public void setAnnotationMethod(AnnotationMethod annotationMethod) {
        this.annotationMethod = annotationMethod;
    }

    public Chromatogram getChromatogram() {
        return this.chromatogram;
    }

    public void setChromatogram(Chromatogram chromatogram) {
        this.chromatogram = chromatogram;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.basecallingAnnotationId;
    }
}
