package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Chromatogram generated by hbm2java
 */
public class Chromatogram extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "Chromatogram";
    private Integer chromatogramId;
    private Set basecallingAnnotations = new HashSet(0);

    public Chromatogram() {
    }

    public Chromatogram(Set basecallingAnnotations) {
        this.basecallingAnnotations = basecallingAnnotations;
    }

    public Integer getChromatogramId() {
        return this.chromatogramId;
    }

    public void setChromatogramId(Integer chromatogramId) {
        this.chromatogramId = chromatogramId;
    }

    public Set getBasecallingAnnotations() {
        return this.basecallingAnnotations;
    }

    public void setBasecallingAnnotations(Set basecallingAnnotations) {
        this.basecallingAnnotations = basecallingAnnotations;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
       return this.chromatogramId;
    }
}
