package edu.uncc.genosets.datamanager.entity;
// Generated Feb 27, 2014 4:44:59 PM by Hibernate Tools 3.2.1.GA

/**
 * DbFile generated by hbm2java
 */
public class DbFile extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "DbFile";
    private Integer fileId;
    private String fileName;
    private String fileType;
    private String fileExtension;
    private byte[] fileContent;

    public DbFile() {
    }

    public DbFile(Integer fileId, String fileName) {
        this.fileId = fileId;
        this.fileName = fileName;
    }

    public DbFile(Integer fileId, String fileName, String fileType, String fileExtension, byte[] fileContent) {
        this.fileId = fileId;
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileExtension = fileExtension;
        this.fileContent = fileContent;
    }

    public Integer getFileId() {
        return fileId;
    }

    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileType() {
        return fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getFileExtension() {
        return fileExtension;
    }

    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    public byte[] getFileContent() {
        return fileContent;
    }

    public void setFileContent(byte[] fileContent) {
        this.fileContent = fileContent;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return fileId;
    }
}
