package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * FeatureDetailType generated by hbm2java
 */
public class FeatureDetailType extends CustomizableEntity   implements java.io.Serializable {
    public static final String DEFAULT_NAME = "FeatureDetailType";

     private Integer featureDetailTypeId;
     private String detailCategory;
     private String detailType;
     private Set featureAnnotationDetails = new HashSet(0);
     private Set featureAnnotationDetails_1 = new HashSet(0);

    public FeatureDetailType() {
    }

    public FeatureDetailType(String detailCategory, String detailType, Set featureAnnotationDetails, Set featureAnnotationDetails_1) {
       this.detailCategory = detailCategory;
       this.detailType = detailType;
       this.featureAnnotationDetails = featureAnnotationDetails;
       this.featureAnnotationDetails_1 = featureAnnotationDetails_1;
    }
   
    public Integer getFeatureDetailTypeId() {
        return this.featureDetailTypeId;
    }
    
    public void setFeatureDetailTypeId(Integer featureDetailTypeId) {
        this.featureDetailTypeId = featureDetailTypeId;
    }
    public String getDetailCategory() {
        return this.detailCategory;
    }
    
    public void setDetailCategory(String detailCategory) {
        this.detailCategory = detailCategory;
    }
    public String getDetailType() {
        return this.detailType;
    }
    
    public void setDetailType(String detailType) {
        this.detailType = detailType;
    }
    public Set getFeatureAnnotationDetails() {
        return this.featureAnnotationDetails;
    }
    
    public void setFeatureAnnotationDetails(Set featureAnnotationDetails) {
        this.featureAnnotationDetails = featureAnnotationDetails;
    }
    public Set getFeatureAnnotationDetails_1() {
        return this.featureAnnotationDetails_1;
    }
    
    public void setFeatureAnnotationDetails_1(Set featureAnnotationDetails_1) {
        this.featureAnnotationDetails_1 = featureAnnotationDetails_1;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.featureDetailTypeId;
    }
}


