package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

/**
 * FeatureClusterByOrganism generated by hbm2java
 */
public class FeatureClusterByOrganism extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "FeatureClusterByOrganism";
    private Integer featureClusterByOrganismId;
    private Organism organismByOrganism;
    private Feature feature;
    private FeatureCluster featureCluster;
    private AnnotationMethod annotationMethod;
    private AssembledUnit assembledUnit;
    private Organism organismByComparedOrganism;
    private Integer countByOrganism;
    private Integer countByFeatureOrganism;

    public FeatureClusterByOrganism() {
    }

    public FeatureClusterByOrganism(Organism organismByOrganism, Feature feature, FeatureCluster featureCluster, AnnotationMethod annotationMethod, AssembledUnit assembledUnit, Organism organismByComparedOrganism, Integer countByOrganism, Integer countByFeatureOrganism) {
        this.organismByOrganism = organismByOrganism;
        this.feature = feature;
        this.featureCluster = featureCluster;
        this.annotationMethod = annotationMethod;
        this.assembledUnit = assembledUnit;
        this.organismByComparedOrganism = organismByComparedOrganism;
        this.countByOrganism = countByOrganism;
        this.countByFeatureOrganism = countByFeatureOrganism;
    }

    public Integer getFeatureClusterByOrganismId() {
        return this.featureClusterByOrganismId;
    }

    public void setFeatureClusterByOrganismId(Integer featureClusterByOrganismId) {
        this.featureClusterByOrganismId = featureClusterByOrganismId;
    }

    public Organism getOrganismByOrganism() {
        return this.organismByOrganism;
    }

    public void setOrganismByOrganism(Organism organismByOrganism) {
        this.organismByOrganism = organismByOrganism;
    }

    public Feature getFeature() {
        return this.feature;
    }

    public void setFeature(Feature feature) {
        this.feature = feature;
    }

    public FeatureCluster getFeatureCluster() {
        return this.featureCluster;
    }

    public void setFeatureCluster(FeatureCluster featureCluster) {
        this.featureCluster = featureCluster;
    }

    public AnnotationMethod getAnnotationMethod() {
        return this.annotationMethod;
    }

    public void setAnnotationMethod(AnnotationMethod annotationMethod) {
        this.annotationMethod = annotationMethod;
    }

    public AssembledUnit getAssembledUnit() {
        return this.assembledUnit;
    }

    public void setAssembledUnit(AssembledUnit assembledUnit) {
        this.assembledUnit = assembledUnit;
    }

    public Organism getOrganismByComparedOrganism() {
        return this.organismByComparedOrganism;
    }

    public void setOrganismByComparedOrganism(Organism organismByComparedOrganism) {
        this.organismByComparedOrganism = organismByComparedOrganism;
    }

    public Integer getCountByOrganism() {
        return this.countByOrganism;
    }

    public void setCountByOrganism(Integer countByOrganism) {
        this.countByOrganism = countByOrganism;
    }

    public Integer getCountByFeatureOrganism() {
        return this.countByFeatureOrganism;
    }

    public void setCountByFeatureOrganism(Integer countByFeatureOrganism) {
        this.countByFeatureOrganism = countByFeatureOrganism;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }
    
    @Override
    public Integer getId() {
        return this.featureClusterByOrganismId;
    }
}
