package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * FeatureCluster generated by hbm2java
 */
public class FeatureCluster extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "FeatureCluster";
    private Integer featureClusterId;
    private String clusterCategory;
    private String clusterType;
    private String clusterName;

    public FeatureCluster() {
    }

    public FeatureCluster(String clusterCategory, String clusterType, String clusterName) {
        this.clusterCategory = clusterCategory;
        this.clusterType = clusterType;
        this.clusterName = clusterName;
    }

    public Integer getFeatureClusterId() {
        return this.featureClusterId;
    }

    public void setFeatureClusterId(Integer featureClusterId) {
        this.featureClusterId = featureClusterId;
    }

    public String getClusterCategory() {
        return this.clusterCategory;
    }

    public void setClusterCategory(String clusterCategory) {
        this.clusterCategory = clusterCategory;
    }

    public String getClusterType() {
        return this.clusterType;
    }

    public void setClusterType(String clusterType) {
        this.clusterType = clusterType;
    }

    public String getClusterName() {
        return this.clusterName;
    }

    public void setClusterName(String clusterName) {
        this.clusterName = clusterName;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FeatureCluster other = (FeatureCluster) obj;
        if (this.featureClusterId != other.featureClusterId && (this.featureClusterId == null || !this.featureClusterId.equals(other.featureClusterId))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + (this.featureClusterId != null ? this.featureClusterId.hashCode() : 0);
        return hash;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }

    @Override
    public Integer getId() {
        return this.featureClusterId;
    }
}
