package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * MolecularSequence generated by hbm2java
 */
public class MolecularSequence extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "MolecularSequence";
    //sequence types
    public static final String TYPE_NUCLEOTIDE = "Nucleotide";
    public static final String TYPE_PROTEIN = "Protein";
    private Integer molecularSequenceId;
    private String sequenceType;
    private String forwardSequence;
    
    private Set assembledUnits = new HashSet(0);
    private Set featuresForAssembledSequence = new HashSet(0);
    private Set assembledUnitAquisitions = new HashSet(0);
    private Set assembledUnits_1 = new HashSet(0);
    private Set featuresForProteinSequence = new HashSet(0);
    private Set featuresForAssembledSequence_1 = new HashSet(0);
    private Set assembledUnitAquisitions_1 = new HashSet(0);
    private Set featuresForProteinSequence_1 = new HashSet(0);

    public MolecularSequence() {
    }

    public MolecularSequence(String sequenceType, String forwardSequence, Set assembledUnits, Set featuresForAssembledSequence, Set assembledUnitAquisitions, Set assembledUnits_1, Set featuresForProteinSequence, Set featuresForAssembledSequence_1, Set assembledUnitAquisitions_1, Set featuresForProteinSequence_1) {
        this.sequenceType = sequenceType;
        this.forwardSequence = forwardSequence;
        this.assembledUnits = assembledUnits;
        this.featuresForAssembledSequence = featuresForAssembledSequence;
        this.assembledUnitAquisitions = assembledUnitAquisitions;
        this.assembledUnits_1 = assembledUnits_1;
        this.featuresForProteinSequence = featuresForProteinSequence;
        this.featuresForAssembledSequence_1 = featuresForAssembledSequence_1;
        this.assembledUnitAquisitions_1 = assembledUnitAquisitions_1;
        this.featuresForProteinSequence_1 = featuresForProteinSequence_1;
    }

    public Integer getMolecularSequenceId() {
        return this.molecularSequenceId;
    }

    public void setMolecularSequenceId(Integer molecularSequenceId) {
        this.molecularSequenceId = molecularSequenceId;
    }

    public String getSequenceType() {
        return this.sequenceType;
    }

    public void setSequenceType(String sequenceType) {
        this.sequenceType = sequenceType;
    }

    public String getForwardSequence() {
        return this.forwardSequence;
    }

    public void setForwardSequence(String forwardSequence) {
        this.forwardSequence = forwardSequence;
    }

    public Set getAssembledUnits() {
        return this.assembledUnits;
    }

    public void setAssembledUnits(Set assembledUnits) {
        this.assembledUnits = assembledUnits;
    }

    public Set getFeaturesForAssembledSequence() {
        return this.featuresForAssembledSequence;
    }

    public void setFeaturesForAssembledSequence(Set featuresForAssembledSequence) {
        this.featuresForAssembledSequence = featuresForAssembledSequence;
    }

    public Set getAssembledUnitAquisitions() {
        return this.assembledUnitAquisitions;
    }

    public void setAssembledUnitAquisitions(Set assembledUnitAquisitions) {
        this.assembledUnitAquisitions = assembledUnitAquisitions;
    }

    public Set getAssembledUnits_1() {
        return this.assembledUnits_1;
    }

    public void setAssembledUnits_1(Set assembledUnits_1) {
        this.assembledUnits_1 = assembledUnits_1;
    }

    public Set getFeaturesForProteinSequence() {
        return this.featuresForProteinSequence;
    }

    public void setFeaturesForProteinSequence(Set featuresForProteinSequence) {
        this.featuresForProteinSequence = featuresForProteinSequence;
    }

    public Set getFeaturesForAssembledSequence_1() {
        return this.featuresForAssembledSequence_1;
    }

    public void setFeaturesForAssembledSequence_1(Set featuresForAssembledSequence_1) {
        this.featuresForAssembledSequence_1 = featuresForAssembledSequence_1;
    }

    public Set getAssembledUnitAquisitions_1() {
        return this.assembledUnitAquisitions_1;
    }

    public void setAssembledUnitAquisitions_1(Set assembledUnitAquisitions_1) {
        this.assembledUnitAquisitions_1 = assembledUnitAquisitions_1;
    }

    public Set getFeaturesForProteinSequence_1() {
        return this.featuresForProteinSequence_1;
    }

    public void setFeaturesForProteinSequence_1(Set featuresForProteinSequence_1) {
        this.featuresForProteinSequence_1 = featuresForProteinSequence_1;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }
    
    @Override
    public Integer getId() {
        return this.molecularSequenceId;
    }
}
