package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Organism generated by hbm2java
 */
@XmlRootElement
public class Organism extends CustomizableEntity implements java.io.Serializable {

    public static final String DEFAULT_NAME = "Organism";
    public final static String PROP_TAXONOMYID = "taxonomyIdentifier";
    private Integer organismId;
    private String kingdom;
    private String phylum;
    private String taxClass;
    private String taxOrder;
    private String family;
    private String genus;
    private String species;
    private String strain;
    private String sample;
    private String shortName;
    private Integer taxonomyIdentifier;
    private String projectId;

    public Organism() {
    }

  

    public Integer getOrganismId() {
        return this.organismId;
    }

    public void setOrganismId(Integer organismId) {
        this.organismId = organismId;
    }

    public String getKingdom() {
        return this.kingdom;
    }

    public void setKingdom(String kingdom) {
        this.kingdom = kingdom;
    }

    public String getPhylum() {
        return this.phylum;
    }

    public void setPhylum(String phylum) {
        this.phylum = phylum;
    }

    public String getTaxClass() {
        return this.taxClass;
    }

    public void setTaxClass(String taxClass) {
        this.taxClass = taxClass;
    }

    public String getTaxOrder() {
        return this.taxOrder;
    }

    public void setTaxOrder(String taxOrder) {
        this.taxOrder = taxOrder;
    }

    public String getFamily() {
        return this.family;
    }

    public void setFamily(String family) {
        this.family = family;
    }

    public String getGenus() {
        return this.genus;
    }

    public void setGenus(String genus) {
        this.genus = genus;
    }

    public String getSpecies() {
        return this.species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public String getStrain() {
        return this.strain;
    }

    public void setStrain(String strain) {
        this.strain = strain;
    }

    public String getSample() {
        return this.sample;
    }

    public void setSample(String sample) {
        this.sample = sample;
    }

    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    public Integer getTaxonomyIdentifier() {
        return this.taxonomyIdentifier;
    }

    public void setTaxonomyIdentifier(Integer taxonomyIdentifier) {
        this.taxonomyIdentifier = taxonomyIdentifier;
    }

    /**
     * @return the projectId
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * @param projectId the projectId to set
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Organism other = (Organism) obj;
        if (this.organismId != other.organismId && (this.organismId == null || !this.organismId.equals(other.organismId))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + (this.organismId != null ? this.organismId.hashCode() : 0);
        return hash;
    }

    @Override
    public String getDefaultName() {
        return DEFAULT_NAME;
    }
    
    @Override
    public Integer getId() {
        return this.organismId;
    }
}
