package edu.uncc.genosets.datamanager.entity;
// Generated Oct 3, 2010 3:29:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SeqRead generated by hbm2java
 */
public class SeqRead  implements java.io.Serializable {
    public static final String DEFAULT_NAME = "SeqRead";

     private Integer seqReadId;
     private Integer organism;
     private Integer molecularSequence;
     private String readType;
     private String readName;
     private Integer readLength;
     private Set readAssemblies = new HashSet(0);
     private Set basecallingAnnotations = new HashSet(0);

    public SeqRead() {
    }

    public SeqRead(Integer organism, Integer molecularSequence, String readType, String readName, Integer readLength, Set readAssemblies, Set basecallingAnnotations) {
       this.organism = organism;
       this.molecularSequence = molecularSequence;
       this.readType = readType;
       this.readName = readName;
       this.readLength = readLength;
       this.readAssemblies = readAssemblies;
       this.basecallingAnnotations = basecallingAnnotations;
    }
   
    public Integer getSeqReadId() {
        return this.seqReadId;
    }
    
    public void setSeqReadId(Integer seqReadId) {
        this.seqReadId = seqReadId;
    }
    public Integer getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Integer organism) {
        this.organism = organism;
    }
    public Integer getMolecularSequence() {
        return this.molecularSequence;
    }
    
    public void setMolecularSequence(Integer molecularSequence) {
        this.molecularSequence = molecularSequence;
    }
    public String getReadType() {
        return this.readType;
    }
    
    public void setReadType(String readType) {
        this.readType = readType;
    }
    public String getReadName() {
        return this.readName;
    }
    
    public void setReadName(String readName) {
        this.readName = readName;
    }
    public Integer getReadLength() {
        return this.readLength;
    }
    
    public void setReadLength(Integer readLength) {
        this.readLength = readLength;
    }
    public Set getReadAssemblies() {
        return this.readAssemblies;
    }
    
    public void setReadAssemblies(Set readAssemblies) {
        this.readAssemblies = readAssemblies;
    }
    public Set getBasecallingAnnotations() {
        return this.basecallingAnnotations;
    }
    
    public void setBasecallingAnnotations(Set basecallingAnnotations) {
        this.basecallingAnnotations = basecallingAnnotations;
    }




}


