/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.orthomcl;

import java.io.File;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.NbPreferences;

/**
 *
 * @author lucy
 */
public class BlastSettingsVisualPanel_1 extends javax.swing.JPanel {

    /**
     * Creates new form BlastSettingsVisualPanel
     */
    public BlastSettingsVisualPanel_1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "BLAST settings";
    }

    public JTextArea getBlastpText() {
        return blastpText;
    }

    public void setBlastpText(JTextArea blastpText) {
        this.blastpText = blastpText;
    }

    public JTextArea getMakeblastdbText() {
        return makeblastdbText;
    }

    public void setMakeblastdbText(JTextArea makeblastdbText) {
        this.makeblastdbText = makeblastdbText;
    }

    public JTextField getBlastBinText() {
        return blastBinText;
    }

    public void setBlastBinText(JTextField blastBinText) {
        this.blastBinText = blastBinText;
    }

    public JCheckBox getBlastpCheck() {
        return blastpCheck;
    }

    public void setBlastpCheck(JCheckBox blastpCheck) {
        this.blastpCheck = blastpCheck;
    }

    public JCheckBox getMakeBlastDbCheck() {
        return makeBlastDbCheck;
    }

    public void setMakeBlastDbCheck(JCheckBox makeBlastDbCheck) {
        this.makeBlastDbCheck = makeBlastDbCheck;
    }

    public JButton getBrowseButton() {
        return browseButton;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        blastpText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        makeblastdbText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        blastBinText = new javax.swing.JTextField();
        makeBlastDbCheck = new javax.swing.JCheckBox();
        blastpCheck = new javax.swing.JCheckBox();
        browseButton = new javax.swing.JButton();

        blastpText.setColumns(20);
        blastpText.setLineWrap(true);
        blastpText.setRows(5);
        blastpText.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.blastpText.text")); // NOI18N
        blastpText.setWrapStyleWord(true);
        jScrollPane2.setViewportView(blastpText);

        makeblastdbText.setColumns(20);
        makeblastdbText.setLineWrap(true);
        makeblastdbText.setRows(5);
        makeblastdbText.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.makeblastdbText.text")); // NOI18N
        makeblastdbText.setWrapStyleWord(true);
        jScrollPane3.setViewportView(makeblastdbText);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.jLabel3.text")); // NOI18N

        blastBinText.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.blastBinText.text")); // NOI18N

        makeBlastDbCheck.setSelected(true);
        makeBlastDbCheck.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.makeBlastDbCheck.text")); // NOI18N

        blastpCheck.setSelected(true);
        blastpCheck.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.blastpCheck.text")); // NOI18N

        browseButton.setText(org.openide.util.NbBundle.getMessage(BlastSettingsVisualPanel_1.class, "BlastSettingsVisualPanel_1.browseButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blastBinText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeBlastDbCheck)
                            .addComponent(blastpCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(makeBlastDbCheck)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blastpCheck))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(blastBinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blastBinText;
    private javax.swing.JCheckBox blastpCheck;
    private javax.swing.JTextArea blastpText;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox makeBlastDbCheck;
    private javax.swing.JTextArea makeblastdbText;
    // End of variables declaration//GEN-END:variables
}
