/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.orthomcl;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author lucy
 */
public class DbSettingsVisualPanel extends javax.swing.JPanel {

    /**
     * Creates new form DbSettingsVisualPanel
     */
    public DbSettingsVisualPanel() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Database Settings";
    }

    public JCheckBox getDropCreateDatabase() {
        return dropCreateDatabase;
    }


    public JTextField getPasswordText() {
        return passwordText;
    }

    public JTextField getUserNameText() {
        return userNameText;
    }

    public JTextField getDatabaseNameText() {
        return databaseNameText;
    }

    public JTextField getMysqlBin() {
        return mysqlBin;
    }

    public JButton getBrowseButton() {
        return browseButton;
    }

    public JButton getValidateButton() {
        return validateButton;
    }

    public JLabel getValidateLabel() {
        return validateLabel;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dropCreateDatabase = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        databaseNameText = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        passwordText = new javax.swing.JPasswordField();
        mysqlBin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        validateLabel = new javax.swing.JLabel();

        dropCreateDatabase.setSelected(true);
        dropCreateDatabase.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.dropCreateDatabase.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.jLabel2.text")); // NOI18N

        userNameText.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.userNameText.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.jLabel4.text")); // NOI18N

        databaseNameText.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.databaseNameText.text")); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.jTextArea1.text")); // NOI18N
        jTextArea1.setWrapStyleWord(true);

        passwordText.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.passwordText.text")); // NOI18N

        mysqlBin.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.mysqlBin.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.jLabel5.text")); // NOI18N

        browseButton.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.browseButton.text")); // NOI18N

        validateButton.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.validateButton.text")); // NOI18N

        validateLabel.setText(org.openide.util.NbBundle.getMessage(DbSettingsVisualPanel.class, "DbSettingsVisualPanel.validateLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextArea1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameText)
                            .addComponent(databaseNameText)
                            .addComponent(passwordText)))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validateButton))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mysqlBin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dropCreateDatabase)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(databaseNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validateButton)
                    .addComponent(validateLabel))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dropCreateDatabase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mysqlBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField databaseNameText;
    private javax.swing.JCheckBox dropCreateDatabase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mysqlBin;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField userNameText;
    private javax.swing.JButton validateButton;
    private javax.swing.JLabel validateLabel;
    // End of variables declaration//GEN-END:variables
}
