/*
 * Copyright (C) 2014 Aurora Cain
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.uncc.genosets.orthomcl;

import javax.swing.JButton;
import javax.swing.JCheckBox;

/**
 *
 * @author lucy
 */
public class FinalVisualPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinalVisualPanel
     */
    public FinalVisualPanel() {
        initComponents();
    }

    public JCheckBox getExecuteCheckBox() {
        return executeCheckBox;
    }
    
    @Override
    public String getName() {
        return "Finalize";
    }

    public JButton getValidateButton() {
        return validateButton;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        executeCheckBox = new javax.swing.JCheckBox();
        validateButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(executeCheckBox, org.openide.util.NbBundle.getMessage(FinalVisualPanel.class, "FinalVisualPanel.executeCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(validateButton, org.openide.util.NbBundle.getMessage(FinalVisualPanel.class, "FinalVisualPanel.validateButton.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(executeCheckBox)
                    .addComponent(validateButton))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(executeCheckBox)
                .addGap(18, 18, 18)
                .addComponent(validateButton)
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox executeCheckBox;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
}
