/*
 * Copyright (C) 2014 Aurora Cain
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.uncc.genosets.orthomcl;

import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import org.openide.util.NbBundle;

/**
 *
 * @author lucy
 */
@NbBundle.Messages("CTL_GroupingPanelName=FASTA File Settings")
public class GroupingVisualPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form GroupingVisualPanel2
     */
    public GroupingVisualPanel2() {
        initComponents();
    }

    public JRadioButton getFilePerMethodRadio() {
        return filePerMethodRadio;
    }

    public JRadioButton getFilePerOrgRadio() {
        return filePerOrgRadio;
    }

    public JTextField getPrefixStartField() {
        return prefixStartField;
    }

    public JCheckBox getPrefixCheck() {
        return prefixCheck;
    }

    @Override
    public String getName() {
        return Bundle.CTL_GroupingPanelName();
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        filePerOrgRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        filePerMethodRadio = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        prefixCheck = new javax.swing.JCheckBox();
        prefixStartLabel = new javax.swing.JLabel();
        prefixStartField = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();

        buttonGroup1.add(filePerOrgRadio);
        filePerOrgRadio.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(filePerOrgRadio, org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.filePerOrgRadio.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.jLabel1.text")); // NOI18N

        buttonGroup1.add(filePerMethodRadio);
        org.openide.awt.Mnemonics.setLocalizedText(filePerMethodRadio, org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.filePerMethodRadio.text")); // NOI18N

        prefixCheck.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(prefixCheck, org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.prefixCheck.text")); // NOI18N
        prefixCheck.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(prefixStartLabel, org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.prefixStartLabel.text")); // NOI18N

        prefixStartField.setText(org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.prefixStartField.text")); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(GroupingVisualPanel2.class, "GroupingVisualPanel2.jTextArea1.text")); // NOI18N
        jTextArea1.setWrapStyleWord(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextArea1)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filePerOrgRadio)
                            .addComponent(filePerMethodRadio)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prefixCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(prefixStartLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prefixStartField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filePerOrgRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filePerMethodRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prefixCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefixStartLabel)
                    .addComponent(prefixStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton filePerMethodRadio;
    private javax.swing.JRadioButton filePerOrgRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox prefixCheck;
    private javax.swing.JTextField prefixStartField;
    private javax.swing.JLabel prefixStartLabel;
    // End of variables declaration//GEN-END:variables
}
