/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.orthomcl;

import java.io.File;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.NbPreferences;

public final class LoadOrthoMclVisualPanel1 extends JPanel {

    /**
     * Creates new form LoadOrthoMclVisualPanel1
     */
    public LoadOrthoMclVisualPanel1() {
        initComponents();
    }

    public JTextField getFastaFolderText() {
        return fastaFolderText;
    }

    public void setFastaFolderText(JTextField fastaFolderText) {
        this.fastaFolderText = fastaFolderText;
    }

    public JTextField getGroupsFileText() {
        return groupsFileText;
    }

    public void setGroupsFileText(JTextField groupsFileText) {
        this.groupsFileText = groupsFileText;
    }
    
    

    @Override
    public String getName() {
        return "Select Files";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fastaFolderText = new javax.swing.JTextField();
        fastaFolderButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        groupsFileText = new javax.swing.JTextField();
        groupsFileButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(LoadOrthoMclVisualPanel1.class, "LoadOrthoMclVisualPanel1.jLabel1.text")); // NOI18N

        fastaFolderText.setText(org.openide.util.NbBundle.getMessage(LoadOrthoMclVisualPanel1.class, "LoadOrthoMclVisualPanel1.fastaFolderText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(fastaFolderButton, org.openide.util.NbBundle.getMessage(LoadOrthoMclVisualPanel1.class, "LoadOrthoMclVisualPanel1.fastaFolderButton.text")); // NOI18N
        fastaFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastaFolderButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(LoadOrthoMclVisualPanel1.class, "LoadOrthoMclVisualPanel1.jLabel2.text")); // NOI18N

        groupsFileText.setText(org.openide.util.NbBundle.getMessage(LoadOrthoMclVisualPanel1.class, "LoadOrthoMclVisualPanel1.groupsFileText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(groupsFileButton, org.openide.util.NbBundle.getMessage(LoadOrthoMclVisualPanel1.class, "LoadOrthoMclVisualPanel1.groupsFileButton.text")); // NOI18N
        groupsFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fastaFolderText)
                    .addComponent(groupsFileText, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fastaFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupsFileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fastaFolderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fastaFolderButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(groupsFileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupsFileButton))
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fastaFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastaFolderButtonActionPerformed
        //The default dir to use if no value is stored
        File home = new File(System.getProperty("user.home"));
        //Now build a file chooser and invoke the dialog in one line of code
        //"libraries-dir" is our unique key
        File toAdd = new FileChooserBuilder("LoadOrthoMclDirectory").setTitle("Select FASTA Folder").
                setDefaultWorkingDirectory(home).setApproveText("Add").setDirectoriesOnly(true).showOpenDialog();
        //Result will be null if the user clicked cancel or closed the dialog w/o OK
        if (toAdd != null) {
            //set the directory as the parent
            NbPreferences.forModule(FileChooserBuilder.class).put("LoadOrthoMclDirectory", toAdd.getParent());
            //do something
            fastaFolderText.setText(toAdd.getAbsolutePath());
        }
    }//GEN-LAST:event_fastaFolderButtonActionPerformed

    private void groupsFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsFileButtonActionPerformed
        //The default dir to use if no value is stored
        File home = new File(System.getProperty("user.home"));
        //Now build a file chooser and invoke the dialog in one line of code
        //"libraries-dir" is our unique key
        File toAdd = new FileChooserBuilder("LoadOrthoMclDirectory").setTitle("Select Cluster File").
                setDefaultWorkingDirectory(home).setApproveText("Add").setFilesOnly(true).showOpenDialog();
        //Result will be null if the user clicked cancel or closed the dialog w/o OK
        if (toAdd != null) {
            //do something
            NbPreferences.forModule(FileChooserBuilder.class).put("LoadOrthoMclDirectory", toAdd.getParent());
            groupsFileText.setText(toAdd.getAbsolutePath());
        }
    }//GEN-LAST:event_groupsFileButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fastaFolderButton;
    private javax.swing.JTextField fastaFolderText;
    private javax.swing.JButton groupsFileButton;
    private javax.swing.JTextField groupsFileText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
