/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.orthomcl;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import org.openide.util.ImageUtilities;

public final class PathSettingsVisualPanel extends JPanel {

    private final ImageIcon noImage;
    private final ImageIcon warnImage;

    /**
     * Creates new form AssUnitNucFastaVisualPanel1
     */
    public PathSettingsVisualPanel() {
        initComponents();
        this.noImage = ImageUtilities.loadImageIcon("edu/uncc/genosets/icons/no-icon.png", false);
        this.warnImage = ImageUtilities.loadImageIcon("edu/uncc/genosets/icons/warning.png", false);

        this.perlLabel.setIcon(noImage);
        this.orthMclLabel.setIcon(noImage);
        this.mclLabel.setIcon(noImage);
    }

    public void perlIcon(boolean warn) {
        if (warn) {
            this.perlLabel.setIcon(warnImage);
            return;
        }
        this.perlLabel.setIcon(noImage);
    }

    public void orthoMclIcon(boolean warn) {
        if (warn) {
            this.orthMclLabel.setIcon(warnImage);
            return;
        }
        this.orthMclLabel.setIcon(noImage);
    }

    public void mclIcon(boolean warn) {
        if (warn) {
            this.mclLabel.setIcon(warnImage);
            return;
        }
        this.mclLabel.setIcon(noImage);
    }

    @Override
    public String getName() {
        return "Path variables";
    }

    public JTextField getMclBinText() {
        return mclBinText;
    }

    public void setMclBinText(String text) {
        this.mclBinText.setText(text);
    }

    public JTextField getOrthomclBinText() {
        return orthomclBinText;
    }

    public void setOrthomclBinText(String text) {
        this.orthomclBinText.setText(text);
    }

    public JTextField getPerlBinText() {
        return perlBinText;
    }

    public void setPerlBinText(String text) {
        this.perlBinText.setText(text);
    }

    public JRadioButton getWindowsRadioButton() {
        return windowsRadioButton;
    }

    public void setWindowsRadioButton(JRadioButton windowsRadioButton) {
        this.windowsRadioButton = windowsRadioButton;
    }

    public JRadioButton getMacRadioButton() {
        return macRadioButton;
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        perlLabel = new javax.swing.JLabel();
        orthomclBinText = new javax.swing.JTextField();
        orthMclLabel = new javax.swing.JLabel();
        mclLabel = new javax.swing.JLabel();
        perlBinText = new javax.swing.JTextField();
        mclBinText = new javax.swing.JTextField();
        windowsRadioButton = new javax.swing.JRadioButton();
        macRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(perlLabel, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.perlLabel.text")); // NOI18N

        orthomclBinText.setText(org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.orthomclBinText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(orthMclLabel, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.orthMclLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mclLabel, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.mclLabel.text")); // NOI18N

        perlBinText.setText(org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.perlBinText.text")); // NOI18N

        mclBinText.setText(org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.mclBinText.text")); // NOI18N

        buttonGroup1.add(windowsRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(windowsRadioButton, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.windowsRadioButton.text")); // NOI18N
        windowsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(macRadioButton);
        macRadioButton.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(macRadioButton, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.macRadioButton.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.jLabel5.text")); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(org.openide.util.NbBundle.getMessage(PathSettingsVisualPanel.class, "PathSettingsVisualPanel.jTextArea1.text")); // NOI18N
        jTextArea1.setWrapStyleWord(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orthMclLabel)
                            .addComponent(perlLabel)
                            .addComponent(mclLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(orthomclBinText)
                            .addComponent(perlBinText)
                            .addComponent(mclBinText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(macRadioButton)
                                    .addComponent(windowsRadioButton))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextArea1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perlLabel)
                    .addComponent(perlBinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orthMclLabel)
                    .addComponent(orthomclBinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mclLabel)
                    .addComponent(mclBinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(macRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(windowsRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void windowsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsRadioButtonActionPerformed
    }//GEN-LAST:event_windowsRadioButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton macRadioButton;
    private javax.swing.JTextField mclBinText;
    private javax.swing.JLabel mclLabel;
    private javax.swing.JLabel orthMclLabel;
    private javax.swing.JTextField orthomclBinText;
    private javax.swing.JTextField perlBinText;
    private javax.swing.JLabel perlLabel;
    private javax.swing.JRadioButton windowsRadioButton;
    // End of variables declaration//GEN-END:variables
}
