/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.studyset.actions;

import edu.uncc.genosets.studyset.StudySet;
import java.util.HashMap;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

public final class SelectStudySetVisualPanel extends JPanel {

    private DefaultComboBoxModel model;
    private HashMap<Integer, StudySet> map = new HashMap<Integer, StudySet>();
    /**
     * Creates new form CreateStudySetVisualPanel1
     */
    public SelectStudySetVisualPanel() {
        String[] names = new String[1];
        names[0] = "Create New";
        model = new javax.swing.DefaultComboBoxModel(names);
        initComponents();
    }

    @Override
    public String getName() {
        return "Select Study Set";
    }
        
    /**
     * 
     * @return the selected study set or null if create new
     */
    public StudySet getSelectedStudySet(){
       int index = jComboBox1.getSelectedIndex();
       if(index == 0){
           return new StudySet();
       }else{
           return map.get(index);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(model);
        jComboBox1.setSelectedIndex(0);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SelectStudySetVisualPanel.class, "SelectStudySetVisualPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 355, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    void setStudySets(Set<StudySet> filteredSet) {
        int i = 0;
        for (StudySet studySet : filteredSet) {
            model.addElement(studySet.getName());
            map.put((i+1), studySet);
            i++;
        }
    }
}
