/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uncc.genosets.gffloader.download;

import javax.swing.JCheckBox;
import javax.swing.JPanel;

public final class AnnoGffVisualPanel1 extends JPanel {

    /**
     * Creates new form AnnoGffVisualPanel1
     */
    public AnnoGffVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Select Output Formats";
    }

    public JCheckBox getIncludeFastaCheck() {
        return includeFastaCheck;
    }

    public JCheckBox getOrigAssUnitIdCheck() {
        return origAssUnitIdCheck;
    }

    public JCheckBox getAssUnitMappingCheckBox() {
        return assUnitMappingCheckBox;
    }

    public void setAssUnitMappingCheckBox(JCheckBox assUnitMappingCheckBox) {
        this.assUnitMappingCheckBox = assUnitMappingCheckBox;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        includeFastaCheck = new javax.swing.JCheckBox();
        origAssUnitIdCheck = new javax.swing.JCheckBox();
        assUnitMappingCheckBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(includeFastaCheck, org.openide.util.NbBundle.getMessage(AnnoGffVisualPanel1.class, "AnnoGffVisualPanel1.includeFastaCheck.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(origAssUnitIdCheck, org.openide.util.NbBundle.getMessage(AnnoGffVisualPanel1.class, "AnnoGffVisualPanel1.origAssUnitIdCheck.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(assUnitMappingCheckBox, org.openide.util.NbBundle.getMessage(AnnoGffVisualPanel1.class, "AnnoGffVisualPanel1.assUnitMappingCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(includeFastaCheck)
                    .addComponent(origAssUnitIdCheck)
                    .addComponent(assUnitMappingCheckBox))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(includeFastaCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(origAssUnitIdCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assUnitMappingCheckBox)
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox assUnitMappingCheckBox;
    private javax.swing.JCheckBox includeFastaCheck;
    private javax.swing.JCheckBox origAssUnitIdCheck;
    // End of variables declaration//GEN-END:variables
}
